                                                                                                                                                                                                                                                               
Delivered-To: you@example.com, me@example.com
Received: by 10.182.99.201 with SMTP id es9csp17900obb;
        Thu, 23 Jan 2014 06:13:33 -0800 (PST)
X-Received: by 10.66.216.129 with SMTP id oq1mr8219374pac.75.1390486412860;
        Thu, 23 Jan 2014 06:13:32 -0800 (PST)
Return-Path: <support@ish.com.au>
Received: from fish.ish.com.au (eth4368.nsw.adsl.internode.on.net. [59.167.249.15])
        by mx.google.com with ESMTPS id if4si14305814pbc.106.2014.01.23.06.13.32
        for you@example.com, me@example.com
        (version=TLSv1.1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Thu, 23 Jan 2014 06:13:32 -0800 (PST)
Received-SPF: neutral (google.com: 59.167.249.15 is neither permitted nor denied by domain of support@ish.com.au) client-ip=59.167.249.15;
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 59.167.249.15 is neither permitted nor denied by domain of support@ish.com.au) smtp.mail=support@ish.com.au
Received: from ip-21.ish.com.au ([203.29.62.21]:64184 helo=astonish.ish.com.au)
	by fish.ish.com.au with esmtps (TLSv1:AES256-SHA:256)
	(Exim 4.76)
	(envelope-from <support@ish.com.au>)
	id 1W6L21-0006Qk-0V
	for you@example.com, me@example.com; Fri, 24 Jan 2014 01:13:21 +1100
Received: from ish.com.au (localhost [127.0.0.1])
	by astonish.ish.com.au (8.14.7/8.14.7) with ESMTP id s0NEDK8v070472
	for you@example.com, me@example.com; Fri, 24 Jan 2014 01:13:20 +1100 (EST)
	(envelope-from support@ish.com.au)
Date: Thu, 23 Jan 2014 14:12:21 +0000
From: support@ish.com.au
Reply-To: task-19949@squish.ish.com.au
To: you@example.com, me@example.com
Message-ID: <19949.157072.jobsworth@ish.com.au>
References: <19949.157071.jobsworth@ish.com.au>
Subject: [Squish] Reassigned: [#19949] billing report more than 7 days
 [squish]
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Email body...

o------ please reply above this line ------o

[#19949] billing report more than 7 days
----------------------------------------

Vikrant Chaudhary:
*and why.

Description:
1. Go to https://squish.ish.com.au/billing/list?utf8=%E2%9C%93&report[type]=1&report[rows]=1&report[columns]=7&report[filter_project]=0&report[filter_user]=11404&report[worklog_type]=0&report[range]=3&report[start_date]=&report[stop_date]=&report[hide_approved]=0&report[hide_rejected]=0

2. Notice the dates across the top are out of order and they are also missing dates (that is data is missing)


This is quite important since we rely on this report for billing.

Ari


-- 
-------------------------->
Aristedes Maniatis
ish
http://www.ish.com.au
Level 1, 30 Wilson Street Newtown 2042 Australia
phone +61 2 9550 5001   fax +61 2 9550 4001
GPG fingerprint CBFB 84B4 738D 4E87 5E5C  5EFA EF6A 7D2E 3E49 102A

............................................

This task 19949 was just updated with the information above.
If you have any further comments to make, please reply to this email above the line.

To see the history of this task, visit:
https://squish.ish.com.au/tasks/view/19949

-------------------->
squish
